### ISSUE TITLE
businesCode: 13108

### ISSUE THREAD

**Issue by Cloud-Joji** [PAXSTORE/paxstore-openapi-dotnet-sdk#14]
Hi, i configured the external system access in the PAXSTORE applying the access rights, using the IP of my service deployed on Google Cloud. But when i'm trying to get terminals i obtain the "Business Code: 13108, IP Address mismatch".  

My service has the correct configurations so that it can receive and send external requests, trying with other services it works, but with PAXSTORE it doesn't.

Are there any additional considerations for external configuration? such as ports, protocols, etc...

**Comment by paxstore-support** [comment]
Hi, does Google Cloud provide the fix IP address?
You can provide the API call time so that we can check the income IP address.
The external API has call rate limitation and IP address limitation(if configured).

**Comment by Cloud-Joji** [comment]
Hi, yes, Google Cloud provides the fix IP Address.

We using the API with a service called App Engine, this services provides an instance of virtual machine with external ip, usually we use that ip, the problem we have with this is that each new implementation generates a new IP.

So we generate a static ip through a load balancer, all coming from google cloud, to access the service, which does work, the only thing that is not working with this load balancer ip is the connection with the pax market, which requests an ip to establish a connection with the api.

This does not happen when we put the ip of the instance generated by app engine.

**Comment by pax-paxstore** [comment]
Hi, 

As you mentioned, you are using load balancer. I think load balance is help to distribute any request to different implementation. But if call our OPEN API, it means your request will be submitted from your service to our server, I don't think you request will go though load balance server.Instead, I think it will request from the service server directly. Then load balance IP is not the correct IP. You should configure the service IPs directly. .e.g if you have 4 implementations on different servers,  you should configure the these 4 server IPs on marketplace.

**Comment by Cloud-Joji** [comment]
Hello, thank you very much for the prompt response, now I understand, the requests from your service to mine enter through the load balancer, but from my service to yours they do not go through the load balancer, that's why when making requests to the market , it does not find the IP in the white list associated with the market.

I will try to fix this using the API proxy, do you think this work? Make the proxy make the requests from the load balancer ip?

**Comment by Cloud-Joji** [comment]
Solved, I fixed it using another service from my cloud provider, and use a static outbound ip, with VPC, VPC Connector, Routers and NAT Gateway. Redirecting all requests and responses to one static ip.

Thanks.
